[features]
seeds = false
[programs.localnet]
pda_token = "AA6w4TWeM86CJ1CzMsnxboF9d97xQLbcKXBz2vUtkQS7"

[programs.devnet]
pda_token = "AA6w4TWeM86CJ1CzMsnxboF9d97xQLbcKXBz2vUtkQS7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
